### ISSUE TITLE
Look into formik.com

### ISSUE THREAD

**Issue by yvonne-liu** [foundersandcoders/our-site-v3#11]
Currently we're using: 
- Google forms for expression of interest and application
- Airtable for Hire and Tech for Better 

https://formik.com/ (free tier) might be worth trying out.

**Comment by oliverjam** [comment]
The nice thing about Formik is they support submitting any old HTML form to their endpoint.

We can have our own styled `<form action="https://formik.com/our-form-id">` on this site, but still have all the benefits of Google Forms (nice dashboard for responses, automatically send the submitter an email etc)

**Comment by sofer** [comment]
Expressions of interest are currently running at around 150/m, so if we use formik for those we will be in $20/m tier (not saying we shouldn't consider it, though).

**Comment by oliverjam** [comment]
Oh wow, didn't realise we were that high (that's awesome!)

**Comment by oliverjam** [comment]
We're probably never going to use Formik. They pivoted into something different anyway (and never responded when we asked about open source/non-profit pricing tiers)
