### ISSUE TITLE
Skills Bootcamp / pre-apprenticeship programme branding guidelines

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/our-site-v3#163]
We have received branding guidelines. 

We have been asked, at some location on the page where we describe our pre-apprenticeship programme, to use the wording:

_"Skills Bootcamps – part of the Government’s Lifetime Skills Guarantee and Plan for Jobs"._

We are also been asked to add the explanatory text:

_"Skills Bootcamps are flexible courses of up to 16 weeks, giving people the opportunity to build up sector-specific skills and fast-track to an interview with a local employer."_

We have also been asked to use the The Plan for Jobs logo. Logo and guidelines are here:

~~https://www.dropbox.com/sh/tnjlh81zfrcw0sc/AACz6nL6kv9KMy0UYR~~

https://www.dropbox.com/sh/tnjlh81zfrcw0sc/AACz6nL6kv9KMy0UYReJIrida

**Comment by oliverjam** [comment]
> the page where we describe our pre-apprenticeship programme

I don't think we currently have this 😅

**Comment by yvonne-liu** [comment]
I'll get on it.

**Comment by yvonne-liu** [comment]
#177

**Comment by yvonne-liu** [comment]
@sofer The dropbox file you linked does not work (at least for me).

**Comment by sofer** [comment]
@yvonne-liu Corrected link to Plan for Jobs assets: https://www.dropbox.com/sh/tnjlh81zfrcw0sc/AACz6nL6kv9KMy0UYReJIrida

**Comment by oliverjam** [comment]
@sofer do we also need to include the "Funded by the DfE" logo that's in there?
