### ISSUE TITLE
Privacy Notice for Skills Bootcamps

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/our-site-v3#164]
Required in conjunction with the the data collection we are doing. We could just to throw it up as is, rather than turn it into a web page, otoh https://gds.blog.gov.uk/2018/07/16/why-gov-uk-content-should-be-published-in-html-and-not-pdf/

[Skills Bootcamps Privacy Notice for individuals WAVE 2 V1.7.pdf](https://github.com/foundersandcoders/our-site-v3/files/6802563/Skills.Bootcamps.Privacy.Notice.for.individuals.WAVE.2.V1.7.pdf)

**Comment by sofer** [comment]
There is also a Privacy Notice Q&A. We are awaiting guidance on how these documents are to be used.

[Skills Bootcamps PN Q&A Final210621.pdf](https://github.com/foundersandcoders/our-site-v3/files/6806980/Skills.Bootcamps.PN.Q.A.Final210621.pdf)

**Comment by sofer** [comment]
@oliverjam Have you got any strong opinions about where the best place is to park these?

**Comment by oliverjam** [comment]
It would be pretty trivial to paste the PDF text into a Markdown file and host a proper webpage on the site. Do we need to link to them from somewhere?

**Comment by sofer** [comment]
We just need to link them from an AirTable form.

**Comment by sofer** [comment]
@oliverjam the AirTable form is ready, so if there was a "priority-1" label I would probably assign it now.

**Comment by oliverjam** [comment]
Okay I'll try and paste the PDF contents over now

**Comment by sofer** [comment]
I merged the PR and then immediately realised that we need a link from each document to the other document.

**Comment by sofer** [comment]
@oliverjam, just received:

> It is a DfE privacy notice so the ‘we’ and ‘you’ referred to are DfE.
>
> Happy for you to recreate as web pages but absolutely you should make it clear that they are DfE privacy notices and the wording must be an exact copy.
