### ISSUE TITLE
Make cohort-confirm more specific 

### ISSUE THREAD

**Issue by yvonne-liu** [foundersandcoders/our-site-v3#180]
`cohort-confirm` should output the actual date of the cohort instead of `Yes`

- Everything pre-June 18 should say `N/A`(?)
- June 18 - July 15 should say `September 2021`
- July 16 - September 19 should say `January 2022`

**Comment by oliverjam** [comment]
Sorry for the dates in the past do you want me to amend the existing Airtable data?

Changing the form for future EOIs is simple, will do that now
