### ISSUE TITLE
Types of events

### ISSUE THREAD

**Issue by yvonne-liu** [foundersandcoders/our-site-v3#21]
- Short course
	- [ ] Who can come - invite only 
	- [ ] Description
	- [ ] Q&A

- Open Monday evenings (Pairing is caring 🙃)
	- [ ] Description
	- [ ] Q&A 

- Info sessions
 	- [ ] Description

- Workshop - Introduction to Codewars
	- [ ] Description

- Workshop - How to host on GitHub pages 
	- [ ] Description

- Workshop - DOM manipulation 
	- [ ] Description

**Comment by bobbysebolao** [comment]
Looks good! I think it's still worth having the FAQ section on the open Monday evenings page. The question I hear most frequently is whether you can still come if you don't have a laptop.

**Comment by oliverjam** [comment]
we should show the event type on the `/events` page in a little pill thing
