### ISSUE TITLE
TfB question on bottom of the page 

### ISSUE THREAD

**Issue by yvonne-liu** [foundersandcoders/our-site-v3#27]
This question seems out of place: https://www.foundersandcoders.com/tech-for-better#what-is-founders-and-coders-and-what-do-you-do

Could this just be added to the existing Q&A on the page (for now) https://www.foundersandcoders.com/tech-for-better#more-information

**Comment by oliverjam** [comment]
I agree. I assume it was put there for potential T4B partners who hit that page without seeing any others. I don't think it's a good idea to try and make every page self-contained though. If they want to know  who we are they can go to the About page

**Comment by oliverjam** [comment]
Looks like this was removed at some point 😅
