### ISSUE TITLE
Add when does the application close 

### ISSUE THREAD

**Issue by yvonne-liu** [foundersandcoders/our-site-v3#41]
I believe it used to this after "Course dates" and before "How do I apply?":
> Applications close at midnight GMT on the final day of the window

![Screen Shot 2020-04-21 at 9 44 21 AM](https://user-images.githubusercontent.com/22013117/79845259-b27b5300-83b4-11ea-86db-1cace47ea129.png)

Maybe it should say this for the summer and winter application (April and August): 
> Applications close at 23:59 BST on the final day of the window 

and this for the spring application (December): 
> Applications close at 23:59 GMT on the final day of the window

**Comment by oliverjam** [comment]
That sounds good. We'll have to remember to change it for each season though

**Comment by yvonne-liu** [comment]
Outdated and mostly fixed.
