### ISSUE TITLE
Change personnel on About page

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/our-site-v3#68]
![anni](https://user-images.githubusercontent.com/37059/90131653-62117200-dd64-11ea-9018-db45b93f8ffd.jpg)

Add Oli / Gregor / Jack / Anni
Remove Ines / Joe

**Comment by sofer** [comment]
I've removed Ines and Joe. Have asked for an uncropped headshot from @Intersticia. 

@oliverjam @Albadylic @jackherizsmith would you like to add add your own headshots?

**Comment by jackherizsmith** [comment]
happy for you to use my github one https://avatars0.githubusercontent.com/u/58533031?s=460&u=6e85a144ab000bebf09ef9011eb739c4d5607341&v=4

**Comment by oliverjam** [comment]
/about is gone now. We can revisit this if we ever want to bring the personnel bit back
