### ISSUE TITLE
Airtable forms service

### ISSUE THREAD

**Issue by oliverjam** [foundersandcoders/our-site-v3#72]
It would be _reasonably_ easy to set up a Netlify Function that accepts form submissions from the site and forwards them on to the right Airtable. E.g. this form

```html
<form action="/.functions/forms/table-123">
```

would go to our Netlify Function backend, which would turn the submission into JSON and forward on to the `table-123` Airtable base.

This would allow us to self-host a whole bunch of nice forms that we have total control over, but still manage submissions in Airtable like we do now.

**Comment by yvonne-liu** [comment]
Can this be closed for now @oliverjam?

**Comment by oliverjam** [comment]
Yup
